AplicacaoWebHsrTech/Controllers/BankAccountController.cs
using HsrTech.Application.Interface;
using HsrTech.Domain.Entities.Metadata;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AplicacaoWebHsrTech.Controllers
{
    [Authorize]
    public class BankAccountController : Controller
    {
        // GET: BankAccount
        private readonly IBankAccountApp _bankAccountApp;
        
        public BankAccountController(IBankAccountApp bankAccountApp)
        {
            _bankAccountApp = bankAccountApp;            
        }
        public ActionResult Index()
        {
            try
            {
                var list = _bankAccountApp.ListAccountsByLogin(User.Identity.Name);            
                return View(list);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult CreateAccount()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAccount(BankAccountMetadata model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _bankAccountApp.CreateAccount(model.Balance,model.Limit, User.Identity.Name);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult Account(int numberAccount)
        {
            try
            {
                return View(_bankAccountApp.GetAccountByNumberAccount(numberAccount));
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult Transfer(int numberAccount)
        {
            try
            {
                return View(_bankAccountApp.GetAccountByNumberAccount(numberAccount));
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult TransferValue(decimal value, int numberAccount, int typeTransfer, int numberBankAccount )
        {
            try
            {
                if (numberAccount == numberBankAccount)
                {
                    return View();
                }

                bool sucess = _bankAccountApp.Transfer(value, numberAccount, typeTransfer, User.Identity.Name, numberBankAccount);
                if (sucess)
                {
                    return RedirectToAction("Account", "BankAccount");
                    
                }
                else
                {
                    ViewBag.Status = "Erro ao transferir, o valor requerido excede o saldo";
                    return View();

                }                
            }
            catch (Exception ex)
            {

                return View();
            }
        }
    }
}

AplicacaoWebHsrTech/Controllers/LoginController.cs
using HsrTech.Application.Interface;
using HsrTech.Domain.Entities;
using HsrTech.Domain.Entities.Metadata;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace AplicacaoWebHsrTech.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILoginApp _loginApp;
        public LoginController(ILoginApp loginApp)
        {
            _loginApp = loginApp;
        }

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ClientMetadata _client)
        {
            if (ModelState.IsValid)
            {
                if (_loginApp.ValidateLogin(_client.Login, _client.Password))
                {
                    FormsAuthentication.SetAuthCookie(_client.Login, false);
                    return RedirectToAction("Index", "BankAccount");
                }
                else
                {
                    ViewBag.Mensagem = "Login e Senha Inválidos";
                }                
            }
            return View();
        }

        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Login");
        }
    }
}

AplicacaoWebHsrTech/Controllers/SimulationController.cs
using HsrTech.Application.Interface;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AplicacaoWebHsrTech.Controllers
{
    public class SimulationController : Controller
    {
        private readonly ISimulationApp _simulationApp;
        public SimulationController(ISimulationApp simulationApp)
        {
            _simulationApp = simulationApp;
        }
        // GET: Simulation
        public async Task<ActionResult> Index()
        {
            ViewBag.DolarValue = await _simulationApp.GetDolarFromUOLAsync();
            return View();
        }
    }
}

AplicacaoWebHsrTech/Views/BankAccount/Account.cshtml
@model HsrTech.Domain.Entities.BankAccount
@{
    ViewBag.Title = "Conta";
}

<h2>Conta - @Model.NumberAccount</h2>

<table class="table table-responsive">
    <thead class="thead-dark">
        <tr>
            <th>Número da conta</th>
            <th>Saldo</th>
            <th>Limite</th>
            <th></th>
        </tr>
    </thead>
    <tbody>        
        <tr>
            <td>
                @Model.NumberAccount
            </td>
            <td>
                R$ @Model.Balance
            </td>
            <td>
                R$ @Model.Limit
            </td>
            <td>
                <a href="@Url.Action("Transfer","BankAccount", new { numberAccount = Model.NumberAccount})" class="btn btn-default">Transferir</a>
            </td>
        </tr>        
    </tbody>
</table>

AplicacaoWebHsrTech/Views/BankAccount/Chart.cshtml
@model List<HsrTech.Domain.Entities.BankAccount>
@{
    ViewBag.Title = "Gráfico de Criações de Conta";
}

<h2>Clique em um filtro</h2>

<a href="#" onclick="buildChart(0)" class="btn btn-default">Dia</a>
<a href="#" onclick="buildChart(1)" class="btn btn-default">Hora</a>
<a href="#" onclick="buildChart(2)" class="btn btn-default">Minuto</a>

<div id="container" style="width:100%; height:400px;"></div>

<script src="https://code.highcharts.com/highcharts.js"></script>

<script>
    function buildChart(filter){
        $("#container").html("");

        $.post("@Url.Action("GetOpenAccountsBy", "BankAccount")", { filter: filter }, function (response) {
            var dates = new Array();
            var qtds = new Array();
            for (var i in response) {
                dates.push(response[i].Date);
                qtds.push(response[i].Qtd);
            }
            
            var myChart = Highcharts.chart('container', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Gráfico de Contas Criadas por Período'
                },
                xAxis: {
                    categories: dates
                },
                yAxis: {
                    title: {
                        text: 'Quantidade de Contas Criadas'
                    }
                },
                series: [{
                    name: 'Contas Criadas',
                    data: qtds
                }]
            });
        });
    }
</script>

AplicacaoWebHsrTech/Views/BankAccount/CreateAccount.cshtml
@model HsrTech.Domain.Entities.Metadata.BankAccountMetadata
@{
    ViewBag.Title = "CreateAccount";
}

<h2>Criação de conta</h2>

@using (Html.BeginForm("CreateAccount", "BankAccount", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Balance)
        </div>
        <div class="col-md-12">
            @Html.TextBoxFor(m => m.Balance)
            @Html.ValidationMessageFor(m => m.Balance)
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Limit)
        </div>
        <div class="col-md-12">
            @Html.TextBoxFor(m => m.Limit)
            @Html.ValidationMessageFor(m => m.Limit)
        </div>
    </div>
    <input type="submit" value="Criar" class="btn btn-default" />
}

AplicacaoWebHsrTech/Views/BankAccount/Dashboard.cshtml
@using System.Web.UI.WebControls
@model HsrTech.Domain.Entities.ViewModel.DashBoardFilterVM
@{
    ViewBag.Title = "Dashboard";
    ViewBag.Type = new SelectList(new object[]
    {
        new {Name = "By Day", Value = "1"},
        new {Name = "By Hour", Value = "2"},
    new {Name = "By Minute", Value = "2"}
    }, "Value", "Name", selectedValue: (int?)Model?.Type??1);
}

<h2>Dashboard</h2>

<div class="container">
    <form method="get">
        <div class="row">
            <div class="col-md-2">
                Start Date
                @Html.TextBoxFor(model => model.StartDate, new { type = "date" })
            </div>
            <div class="col-md-2">
                End Date
                @Html.TextBoxFor(model => model.EndDate,  new { type = "date" })
            </div>
            <div class="col-md-1">
                Type
                @Html.DropDownList("Type")
                
            </div>
            <div class="col-md-1" style="margin-top: 8px;">
                <button type="submit" class="btn btn-primary" style="vertical-align: middle"><span class="glyphicon glyphicon-filter"></span>Filter</button>
            </div>

        </div>

    </form>

    <div id="chart"></div>
</div>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script>
    let AccountsData = @Html.Raw(Json.Encode(ViewBag.AccountsData));
    let chartCategories = AccountsData.map(a => a.Time);
    let chartData = AccountsData.map(a => a.Quantity);

    Highcharts.chart('chart', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Accounts Created per Time Unit'
        },
        xAxis: {
            categories: chartCategories,
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Number of accounts'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Accounts Created',
            data: chartData

        }]
    });
</script>

AplicacaoWebHsrTech/Views/BankAccount/Index.cshtml
@model List<HsrTech.Domain.Entities.BankAccount>
@{
    ViewBag.Title = "Bank Accounts";
}

<h2>Selecione uma conta</h2>

<a href="@Url.Action("CreateAccount","BankAccount")" class="btn btn-default">Criar conta</a>
<a href="@Url.Action("Chart","BankAccount")" class="btn btn-default">Gráfico de contas criadas</a>

<table class="table table-responsive">
<thead class="thead-dark">
    <tr>
        <th>Número da conta</th>
        <th>Saldo</th>
        <th>Limite</th>
        <th></th>
    </tr>
</thead>
<tbody>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @item.NumberAccount
        </td>
        <td>
            R$ @item.Balance
        </td>
        <td>
            R$ @item.Limit
        </td>
        <td>

            <a href="@Url.Action("Account","BankAccount", new { numberAccount = item.NumberAccount})" class="btn btn-default">Selecionar</a>
        </td>
    </tr>
    }
</tbody>
</table>

AplicacaoWebHsrTech/Views/BankAccount/Statistics.cshtml
@model HsrTech.Domain.Entities.Partial.StatisticsOptions
@{
    ViewBag.Title = "Estatísticas";
}
<script src="https://code.highcharts.com/highcharts.js"></script>

<style>
    #container {
        height: 300px;
        min-width: 310px;
        max-width: 800px;
        margin: 0 auto;
    }
</style>

<form method="POST" id="submit_form">
    <div class="form-group">
        @Html.LabelFor(m => m.GroupMode)
        @Html.EnumDropDownListFor(model => model.GroupMode, new { @id = "mode_input", @class = "form-control" })
    </div>
</form>

<div id="container"></div>

<script>

    $("#mode_input").change(function () {
        $("#submit_form").submit();
    })

    var chartData = @Html.Raw(Json.Encode(ViewBag.DataChart));
    var categories = [];
    var values = [];

    if (chartData.Options.GroupMode > 0) {

        $.each(chartData.Items, function (index, value) {
            category = value.Day + '/' + value.Month + '/' + value.Year + ' ' + value.Hour + ':' + value.Minute;
            categories.push(category);
            values.push(value.Count);
        });
    }
    else {
        $.each(chartData.Items, function (index, value) {
            category = value.Day + '/' + value.Month + '/' + value.Year;
            categories.push(category);
            values.push(value.Count);
        });
    }


    var chart = Highcharts.chart('container', {

        chart: {
            type: 'column'
        },

        xAxis: {
            categories: categories,
            labels: {
                x: -10
            }
        },

        yAxis: {
            allowDecimals: false,
            title: {
                text: 'Amount'
            }
        },

        series: [{
            name: 'Estatísticas de contas criadas',
            data: values
        }],

        responsive: {
            rules: [{
                condition: {
                    maxWidth: 500
                },
                chartOptions: {
                    legend: {
                        align: 'center',
                        verticalAlign: 'bottom',
                        layout: 'horizontal'
                    },
                    yAxis: {
                        labels: {
                            align: 'left',
                            x: 0,
                            y: -5
                        },
                        title: {
                            text: null
                        }
                    },
                    subtitle: {
                        text: null
                    },
                    credits: {
                        enabled: false
                    }
                }
            }]
        }
    });

    chart.setSize(null);


</script>

AplicacaoWebHsrTech/Views/BankAccount/Transfer.cshtml
@model HsrTech.Domain.Entities.BankAccount
@{
    ViewBag.Title = "Transferência";
}

<h2>Transferência</h2>
@Html.HiddenFor(m => m.Balance)
@Html.HiddenFor(m => m.NumberAccount)



<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">Valor da transferência</span>        
    </div>
    <input type="text" id="valor" class="form-control" aria-label="Amount (to the nearest dollar)">
</div>
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">Número da conta</span>
    </div>
    <input type="text" id="nrConta" class="form-control">
</div>
<div class="form-check">
    <input class="form-check-input" type="radio" name="tipoOpcao" id="corrente" value="0" checked>
    <label class="form-check-label" for="corrente">
        Conta Corrente
    </label>
</div>
<div class="form-check">
    <input class="form-check-input" type="radio" name="tipoOpcao" id="credito" value="1">
    <label class="form-check-label" for="credito">
        Crédito
    </label>
</div>

<div style="color:red">@ViewBag.Status</div>
<button onclick="Transferir()">Transferir</button>

<script>
    function Transferir() {
        if ($('#NumberAccount').val() == $('#nrConta').val()) {
            alert("Não é possível transferir para mesma conta!")
            return false;
        } else {
            var valor = $('#valor').val();
            var nrConta = $('#nrConta').val();
            var tipoOpcao = $("input[name='tipoOpcao']:checked").val();
            $.post("@Url.Action("TransferValue","BankAccount")",
                {
                    value: valor,
                    numberAccount: nrConta,
                    typeTransfer: tipoOpcao,
                    numberBankAccount : $('#NumberAccount').val()
                },
            function (response) {
                if (response.erro) {

                }
            });

        }
    }
</script>

AplicacaoWebHsrTech/Views/Login/Index.cshtml
@model HsrTech.Domain.Entities.Metadata.ClientMetadata
@{
                /**/

                ViewBag.Title = "Login";
}

<h2>Faça o seu login</h2>


@using (Html.BeginForm("Index", "Login", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Login)
        </div>
        <div class="col-md-12">
            @Html.TextBoxFor(m => m.Login)
            @Html.ValidationMessageFor(m => m.Login)
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(m => m.Password)
        </div>
        <div class="col-md-12">
            @Html.TextBoxFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
        </div>
    </div>
    <div style="color:red">@ViewBag.Mensagem</div>
    <input type="submit" value="Logar" class="btn btn-default" />
}

AplicacaoWebHsrTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HsrTech</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Banco XPTO", "Index", "BankAccount", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li><a class="nav-item nav-link active" href="@Url.Action("Index","Simulation")">Simular conversão</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a class="nav-item nav-link disabled" href="@Url.Action("Statistics","BankAccount")">Estatísticas</a></li>
                        <li><a class="nav-item nav-link disabled" href="@Url.Action("SignOut","Login")">Sair</a></li>
                    }

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

</body>
</html>

AplicacaoWebHsrTech/Views/Simulation/Index.cshtml
@{
    ViewBag.Title = "Simulador de conversão";
}

<h2>Simulador de conversão</h2>

<input type="hidden" id="valorDolar" value="@ViewBag.DolarValue" />
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">Valor para</span>
    </div>
    <input type="text" id="valor" class="form-control">
</div>
<div class="form-check">
    <input class="form-check-input" type="radio" name="tipoOpcao" id="real" value="0" checked>
    <label class="form-check-label" for="corrente">
        Real
    </label>
</div>
<div class="form-check">
    <input class="form-check-input" type="radio" name="tipoOpcao" id="dolar" value="1">
    <label class="form-check-label" for="credito">
        Dolár
    </label>
</div>

<button class="btn btn-default" onclick="Converter()">Converter</button>
<script>  
    function Converter() {
        var valor = $('#valor').val();
        var valorDolar = $('#valorDolar').val();
        if ($("input[name='tipoOpcao']:checked").val() == 0) {
            alert((parseFloat(valorDolar.replace(",", ".")) * parseFloat(valor.replace(",", "."))).toFixed(2))
        } else {
            alert((parseFloat(valor.replace(",", ".")) / parseFloat(valorDolar.replace(",", "."))).toFixed(2)) 
        }
    }
</script>